platform :ios, "13.0"
use_frameworks!
inhibit_all_warnings!

target "PureSwiftApp" do
    pod 'SnapKit'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxTest'
end

#swift_32 = ['FontAwesome.swift','FontAwesome.swift-FontAwesome.swift']
#swift4 = ['R.swift.Library','SnapKit','SwiftDate','Alamofire']
#
#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        swift_version = nil
#        
#        if swift_32.include?(target.name)
#            print "set pod #{target.name} swift version to 3.2\n"
#            swift_version = '3.2'
#        end
#        
#        if swift4.include?(target.name)
#            print "set pod #{target.name} swift version to 4.0\n"
#            swift_version = '4.0'
#        end
#        
#        if swift_version
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = swift_version
#            end
#        end
#    end
#end


